@startuml

!includeurl https://raw.githubusercontent.com/vishnu2kmohan/puml/master/ipuml/Mesosphere.ipuml

title Mesos Secrets Injection
hide footbox
' To print on US Letter, uncomment the scale directive
'scale 1056*816

'participant SGW as "Service Gateway"
'participant IAM as "Identity and\nAccess Manager"
'participant HOOK as "Secrets\nHook"

actor FW as "Framework"
participant MM as "Mesos Master"
participant MA as "Mesos Agent"
participant MCONT as "Mesos Containerizer"
participant SEI as "Secrets Environment\nIsolator"
participant SVI as "Secrets Volume\nIsolator"
participant SR as "Secrets Resolver"
database SS as "Secrets Store"
participant CONT as "Container"
participant EXEC as "Executor"
participant TASK as "Task(s)"

activate FW
    FW -> MM : TaskInfo with Secret(s)
    activate MM
        MM -> MM : Validate\n(+AuthN+Z)
        note left : Authorize access\nto secret(s) by\nNamespace Mapping
        alt Authorized
            MM -> MA : TaskInfo
            activate MA
                MA -> MCONT : Launch Container
                activate MCONT
                    alt Environment Secret(s)
                        MCONT -> SEI : Retrieve Environment Secret(s)
                        activate SEI
                            loop For each secret
                                SEI -> SR : Resolve Secret
                                activate SR
                                    SR -> SS : Get secret
                                    activate SS
                                        SS -> SS : Validate\n(+AuthN+Z)
                                        alt Valid
                                            SS -> SR : Secret for you!
                                        else Invalid
                                            SS -> SR : No Secret for you!
                                        end
                                    deactivate SS
                                    SR -> SEI : Secret
                                deactivate SR
                            end
                            SEI -> MCONT : Here are your env secret(s)
                        deactivate SEI
                        MCONT -> CONT: Launch Container with Env Secret(s)
                        activate CONT
                            CONT -> EXEC : Inject Env Secret(s)
                            EXEC -> TASK: Inject Env Secret(s)
                        deactivate CONT
                    else Volume Secret(s)
                        MCONT -> SVI : Retrieve Volume Secret(s)
                        activate SVI
                            loop For each secret
                                SVI -> SR : Resolve Secret
                                activate SR
                                    SR -> SS : Get Secret
                                    activate SS
                                        SS -> SS : Validate\n(+AuthN+Z)
                                        alt Valid request
                                            SS -> SR : Secret for you!
                                        else Invalid Request
                                            SS -> SR: No Secret for you!
                                        end
                                    deactivate SS
                                    SR -> SVI : Secret
                                deactivate SR
                                SVI -> SVI : Place secret into agent-common ramfs
                                note left : The agent-wide ramfs is \ncreated during agent init
                                SVI -> SVI : Create ramfs in/for the sandbox and build command list
                            end
                            SVI -> MCONT : Command List
                        deactivate SVI
                        MCONT -> CONT : Launch Container
                        activate CONT
                            CONT -> CONT : Wait while volumes\nare prepared
                            MCONT -> CONT : Inject Volume Secret(s)
                            loop For each secret
                                MCONT -> CONT : mv secret from agent ramfs\nto sandbox ramfs
                                MCONT -> CONT : bind-mount ramfs from sandbox into container
                            end
                            CONT -> EXEC : Inject Volume Secret(s)
                            EXEC -> TASK : Inject Volume Secret(s)
                        deactivate CONT
                    end
                deactivate MCONT
            deactivate MA
        else Unauthorized
            MM -> FW : Unauthorized for Secret(s)
        end
    deactivate MM
deactivate FW

@enduml
