@startuml

!includeurl https://raw.githubusercontent.com/vishnu2kmohan/puml/master/ipuml/Mesosphere.ipuml

title Mesos Secrets Injection
hide footbox
' To print on US Letter, uncomment the scale directive
'scale 1056*816

'participant SGW as "Service Gateway"
'participant IAM as "Identity and\nAccess Manager"
'participant HOOK as "Secrets\nHook"

actor FW as "Framework"
participant MM as "Mesos Master"
participant MA as "Mesos Agent"
participant SEI as "Secrets Environment\nIsolator"
participant SVI as "Secrets Volume\nIsolator"
participant SR as "Secrets Resolver"
database SS as "Secrets Store"
participant CONT as "Containerizer"
participant EXEC as "Executor"
participant TASK as "Task(s)"

activate FW
    FW -> MM : TaskInfo with Secret(s)
    activate MM
        MM -> MM : Validate\n(+AuthN+Z)
        note left : Authorize access\nto secret(s) by\nNamespace Mapping
        alt Authorized
            MM -> MA : TaskInfo
            activate MA
                alt Environment Secret(s)
                    MA -> SEI : Retrieve Environment Secret(s)
                    activate SEI
                        SEI -> SR : Resolve Secret(s)
                        activate SR
                            SR -> SS : Get secret(s)
                            activate SS
                                SS -> SS : Validate\n(+AuthN+Z)
                                alt Valid
                                    SS -> SR : Secret(s) for you!
                                else Invalid
                                    SS -> SR : No Secret(s) for you!
                                end
                            deactivate SS
                            loop For each secret
                                SR -> SEI : Secret
                            end
                        deactivate SR
                        SEI -> MA : Here are your env secret(s)
                    deactivate SEI
                    MA -> CONT : Inject Env Secret(s)
                    CONT -> EXEC : Inject Env Secret(s)
                    EXEC -> TASK: Inject Env Secret(s)
                else Volume Secret(s)
                    MA -> SVI : Retrieve Volume Secret(s)
                    activate SVI
                        SVI -> SR : Resolve Secret(s)
                        activate SR
                            SR -> SS : Get Secret(s)
                            activate SS
                                SS -> SS : Validate\n(+AuthN+Z)
                                alt Valid request
                                    SS -> SR : Secret(s) for you!
                                else Invalid Request
                                    SS -> SR: No Secret(s) for you!
                                end
                            deactivate SS
                            loop For each secret
                                SR -> SVI : Secret
                            end
                        deactivate SR
                        SVI -> SVI : Place secret into agent-common ramfs
                        note left : The agent-wide ramfs is \ncreated during agent init
                        SVI -> SVI : Create ramfs in/for the sandbox and build command list
                        SVI -> MA : Command List
                    deactivate SVI
                    MA -> CONT : Command List
                    loop For each secret
                        CONT -> CONT : mv secret from agent ramfs\nto sandbox ramfs
                        CONT -> CONT : bind-mount ramfs from sandbox into container
                    end
                    CONT -> EXEC : Inject Volume Secret(s)
                    EXEC -> TASK : Inject Volume Secret(s)
                end
            deactivate MA
        else Unauthorized
            MM -> FW : Unauthorized for Secret(s)
        end
    deactivate MM
deactivate FW

@enduml
